### ISSUE TITLE
displayName used by Collection.fromCollectionJsonConfigAndContent seems wrong

### ISSUE THREAD

**Issue by rtyley** [guardian/facia-scala-client#218]
Looking at the Australia Network Front at https://www.theguardian.com/au right now, you will see that the 2nd container (normally called 'Spotlight') is called **'Weekend'**:

![image](https://user-images.githubusercontent.com/52038/61963814-6685b400-afc4-11e9-8c2e-2d770816c0e1.png)

That's correct - at the weekend (it's already the weekend in Australia!) the Fronts Editors manually update https://fronts.gutools.co.uk/editorial/config to set the 'Spotlight' container to have the Display Name of 'Weekend' - after the weekend is over, it's manually renamed back again. This is getting displayed correctly in DotCom.

However, in Ophan, where we use the `facia-scala-client` library to get fronts information, [we are displaying the wrong name](https://dashboard.ophan.co.uk/info?path=/commentisfree/2019/jul/26/the-untold-story-of-when-donald-trump-met-boris-johnson#how-did-we-promote-this-on-www-theguardian-com) for the container - we display 'Spotlight', _not_ 'Weekend':

![image](https://user-images.githubusercontent.com/52038/61963083-d2ffb380-afc2-11e9-8311-5b331223da87.png)

The [name Ophan displays comes from](https://github.com/guardian/ophan/blob/2ccbcdb08a1f71fb47f5c86d1def120f2e23570a/trigr/app/fronts/service/PromotionPoller.scala#L54-L60) the `com.gu.facia.api.models.Collection#displayName` field - that field is populated inside the `fapi-client` code by `com.gu.facia.api.models.Collection#fromCollectionJsonConfigAndContent`:

https://github.com/guardian/facia-scala-client/blob/51ce5edfd2905d192a640cfb7e8b7880ee1a3a88/fapi-client/src/main/scala/com/gu/facia/api/models/collection.scala#L23-L26

If you look at that code, you'll see that `collectionJson.displayName`is being used in preference to `collectionConfig.displayName` - is this the wrong way round?!

![image](https://user-images.githubusercontent.com/52038/61964129-1824e500-afc5-11e9-92ac-d705c84af8cf.png)

cc @jonathonherbert @simone-smith

**Comment by jonathonherbert** [comment]
After a chat with @rtyley and @simone-smith , we're not really sure why we'd defer to the collection `displayName` here.

If we create new containers in the config tool, and add content, the `displayName` we choose appears in the collection config but not the collection. Older containers, however, seem to have a `displayName` property, hence the odd behaviour documented above. It's not clear how they got there.

@Reettaphant, I wonder if you know -- is there any old behaviour on client or server that might explain how these `displayName` properties were added to collections, and better yet, whether we'd want to defer to them in this API?
