### ISSUE TITLE
Runtime compatibility errors (eg `NoSuchMethodError`)

### ISSUE THREAD

**Issue by rtyley** [guardian/facia-scala-client#301]
The `fapi-client` libraries depend on several Guardian libraries that can easily become incompatible with each other:

* `content-api-client`
* `content-api-models`
* ...

When app servers use `fapi-client` and (possibly independently) `content-api-client`/`content-api-models`, the ultimate versions of those libraries used can be binary-incompatible. This will lead to fatal runtime errors at unpredictable times.

### How unpredictable are these runtime errors?

Upgrading to `fapi-client` [v4.0.6](https://github.com/guardian/facia-scala-client/releases/tag/v4.0.6) led to fatal errors on **in production** on [fronts.gutools.co.uk](https://fronts.gutools.co.uk/) - not immediately on startup, but **when a user made a search query that _happened_ to return podcast results**. This is obviously very hard to anticipate and test for.

The upgrade that caused this issue was actually [content-api-models v17.5.1 → v17.5.2](https://github.com/guardian/content-api-models/compare/v17.5.1...v17.5.2) - a very innocent-looking change.

### What can we do?

See [_PREVENTING VERSION CONFLICTS WITH VERSIONSCHEME_](https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html#versionscheme-librarydependencyschemes-and-sbt-150) - in summary, you need all 3 of these things:

* **Easy** : Use sbt 1.5.0 or higher everywhere (well, we're probably already doing that)
* **Easy** : Add `ThisBuild / versionScheme := Some("early-semver")` configuration to libraries we want to provide protection for (eg [facia-scala-client](https://github.com/guardian/facia-scala-client), [content-api-scala-client](https://github.com/guardian/content-api-scala-client), [content-api-models](https://github.com/guardian/content-api-models), etc)
* **Hard** : ensure that library updates are released with correctly incremented `major.minor.patch` version number updates, that respect [Scala's Recommended Versioning Scheme](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#versioning-scheme---communicating-compatibility-breakages), which is an extended set of rules adding on to plain [semver](https://semver.org/).

This last part is being addressed with https://github.com/guardian/gha-scala-library-release-workflow and `sbt-version-policy`.

**Comment by davidfurey** [comment]
@roberto https://github.com/guardian/facia-scala-client/pull/305 suggests that this isn't required, can we close this issue?

**Comment by rtyley** [comment]
Very happy indeed we can now close it!
