### ISSUE TITLE
Hitting a hard limit on CAPI for queries with more that 50 items for hydrate.

### ISSUE THREAD

**Issue by DiegoVazquezNanini** [guardian/facia-scala-client#86]
Hi guys,

We are getting errors for CAPI queries with more that 50 internal codes to hydrate.
I think we need to issue multiple queries or enforce a hard limit on the tools.
At least we need a better way to deal with this situations.

Response from CAPI:
{
"response":
"status": "error",
"message": "IDs parameter cannot contain more than 50 items"
}

Furthermore, this is the message that percolates upstream.
"errorMessage": "Failed to hydrate content Bad Request"
This could be a good opportunity improve it. 
ContentApi.getHydrateResponse is the functions that deals with this request.

**Comment by piuccio** [comment]
This was fixed in `0.60`
